bash layer_grad_cam_concept_interpret.sh "" "has_bill_shape" "--save-100-local"
bash layer_grad_cam_concept_interpret.sh "" "has_wing_color" "--save-100-local"
bash layer_grad_cam_concept_interpret.sh "" "has_upperparts_color" "--save-100-local"
bash layer_grad_cam_concept_interpret.sh "" "has_underparts_color" "--save-100-local"
bash layer_grad_cam_concept_interpret.sh "" "has_breast_pattern" "--save-100-local"
bash layer_grad_cam_concept_interpret.sh "" "has_back_color" "--save-100-local"
bash layer_grad_cam_concept_interpret.sh "" "has_tail_shape" "--save-100-local"

bash integrated_grad_concept_interpret.sh "" "has_bill_shape" "--save-100-local"
bash integrated_grad_concept_interpret.sh "" "has_wing_color" "--save-100-local"
bash integrated_grad_concept_interpret.sh "" "has_upperparts_color" "--save-100-local"
bash integrated_grad_concept_interpret.sh "" "has_underparts_color" "--save-100-local"
bash integrated_grad_concept_interpret.sh "" "has_breast_pattern" "--save-100-local"
bash integrated_grad_concept_interpret.sh "" "has_back_color" "--save-100-local"
bash integrated_grad_concept_interpret.sh "" "has_tail_shape" "--save-100-local"